### ISSUE TITLE
PoC: generate self-extracting archive for Windows under Linux

### ISSUE THREAD

**Issue by vkhazin** [vk-twiconnect/sfx-creator-service#1]
# Overview

* Generate a self-extracting archive with an exe extension on Linux
* Compress any 5 files, exe, text, xml, json, and jpeg using Linux command line
* Document steps to set up and to test

## Acceptance criteria:

* Generate self-extracting archive generated on Linux
* Copy the generated archive from Linux to Windows
* Double-click on Windows XP and up to extract with no additional software required
* Readme.md documentation completed
* Setup shell script is provided

The following might be of assistance:
http://www.peazip.org/peazip-command-line.html

**Comment by vkhazin** [comment]
Solutions courtesy of Victor Selyukov 

wget --no-check-certificate http://dej.in.ua/wp-content/uploads/2012/12/unzipsfx-552_win32.tar.gz
$tar xzf unzipsfx-552_win32.tar.gz

$zip -r ./YourArchive.zip ./YourFolder

$cat unzipsfx-552_win32/unzipsfx.exe YourArchive.zip > sfx.exe
$zip -A sfx.exe

Subsequent comment:
tar -zxf (минус потерялся)
Там могут быть проблемы с кирилическими именами файлов в каталоге.

**Comment by ehwest** [comment]
unzipsfx is a _modified_ version of unzip designed to be prepended to existing (Linux-based) .zip archives in order to form self-extracting archives. Instead of taking its first non-flag argument to be the zipfile(s) to be extracted, unzipsfx seeks itself under the name by which it was invoked and tests or extracts the contents of the appended archive.

For security purposes, we probably should source code  from http://infozip.sourceforge.net/ to compile this program on a Win32 machine for our own use in a microservice.  Unfortunately, it seems the sourcecode is hard to find.   Question:  where is this source code and does it compile on a Win32 machine for use in this fashion?
  

 Seems like the PoC should show that can be done?
